### PR TITLE
Farmer personal details implementation

### PR DESCRIPTION
**Pull request by nickwxo**
The 'farmers' endpoints in the API now return a farmer's personal information (Name, DOB, Gender, Verification Status, etc. These fields were contained in a separate ABIS table. Also, we will use the new 'Stakeholder_Num' field to retrieve the farmer associated with a receipt book.

### CODE REVIEW

**Comment by nickwxo** [comment]
@matjames007 Please review when you can.

**Review by matjames007 — CHANGES_REQUESTED** [review]
The personal details added to this endpoint looks good - but shouldn't we be restricting access to this information and make changes to the ACL and to the documentation (swagger)?

**Comment by nickwxo** [comment]
@matjames007 This is ready for review again - the documentation and updated ACL permissions have been added.

**Review by matjames007 — APPROVED** [review]
Changes Accepted.

**Pull request merged**
