### PR TITLE
Admin Dashboard Implementation

### PR DESCRIPTION
**Pull request by nickwxo**
This pull request implements the Administrator Dashboard at the /#/admin location. Each of the pages (listing user accounts, apps, roles, user activity logs, app activity logs) has been implemented in table format. These tables are searchable and paginated.

Also, the pull request includes logging functionality from that branch because it was necessary to merge that branch into this one to implement the logging-related screens on the Admin Dashboard.

N.B. Admins are also supposed to be able to interact with users and apps by banning and disabling them respectively. This has not been implemented yet and should be reflected in the JIRA user stories (in case those stories have not been created yet).

@matjames007 Please try to review this and the other outstanding pull requests today if you can so we can iron out any issues and have everything merged into develop and deployed to a staging environment in time for Monday afternoon's demo @ RADA.

### CODE REVIEW

**Comment by matjames007** [comment]
Very poor attempt at implementing this administrative screens, controllers and services.  As a developer you should take pride in writing as few lines of code as possible.  These commits show absolutely no thought was put into the development.  The commenting is preschool at best.

**Comment by nickwxo** [comment]
@matjames007 Not a very helpful comment since you haven't actually identified specifics of which code you have a problem with... Or any information that could point in the right direction. Perhaps you could try constructive criticism instead of a general insult that provides zero clarification.

**Comment by matjames007** [comment]
@CamiMonte while going through this branch I had to merge the `style.css` file and it broke the look and feel of the administrative UI.  I would appreciate it if you could have a look on it and modify accordingly.

@nick22891 I always give suggestions... nothing I have said is new.  The comment was a precursor to my commit I have just pushed to show how to properly implement the features.

**Review by matjames007 — DISMISSED** [review]
Please review the css for the administrative UI.  Also, a few of the functions that all for filtering are broken and will require adjusting.

**Review by matjames007 — APPROVED** [review]
The important screens, controllers and services are in place.  Will require styling changes and additional features in order to be satisfactory.

**Pull request merged**
