### PR TITLE
Receipts endpoint implementation

### PR DESCRIPTION
**Pull request by nickwxo**
This pull request implements an API endpoint for receipts and returns the receipt book from which a specific receipt # was taken when /receipt/{id} is accessed.

### CODE REVIEW

**Comment by nickwxo** [comment]
@matjames007 Please review when you can.

**Review by matjames007 — CHANGES_REQUESTED** [review]
I think this is ready to be merged.  However I think all the fields should be restricted from the public.  @nick22891 could you make the changes to restrict this?

**Comment by nickwxo** [comment]
@matjames007 This is ready for review again - the documentation and updated ACL permissions have been added.

**Review by matjames007 — APPROVED** [review]
Requested changes have been made.  Accepting and merging into develop

**Pull request merged**
