### PR TITLE
This pull request allows a logged in user to change their password.

### PR DESCRIPTION
**Pull request by leechristophermurray**
A logged in user can now change their password. This was implemented by:

* clearing the `.current_user.us_password` variable in ` CurrentUserFactory.query` so the "New Password" field of `profile.html` is empty when a user signs in/logs in.
* setting up a function, `chpass()`, in `user-ctrl.js` to accept the inputs of the `chpassForm` form in `profile.html`.
*  creating a `PUT` request in `services.js` which was then allowed a route (in `router-user.js`) to submit through `user.js`.
* giving the user feeback based on whether the old password was correct or incorrect.

### CODE REVIEW

**Comment by matjames007** [comment]
The old password must always be used to ensure the request to change a password is coming from the right source.

**Comment by matjames007** [comment]
@nick22891 please review

**Review by nickwxo — CHANGES_REQUESTED** [review]
@thinkking @matjames007 This works fine except if I attempt to change my password having specified an incorrect password as the old password. If I do that, I get an alert message that says "undefined".

I am, however, able to click the Edit button again and correct the old password. The error message given if the user types their existing password incorrectly needs to be (i) not undefined (ii) not a Javascript alert box (though we may have to run with it for the time being).

**Comment by nick22891** [comment]
@thinkking @matjames007 This works fine except if I attempt to change my password having specified an incorrect password as the old password. If I do that, I get an alert message that says "undefined".

I am, however, able to click the Edit button again and correct the old password. The error message given if the user types their existing password incorrectly needs to be (i) not undefined (ii) not a Javascript alert box (though we may have to run with it for the time being).

**Comment by matjames007** [comment]
@thinkking please adjust as @nick22891 described.

**Comment by leechristophermurray** [comment]
@matjames007 and @nick22891 please see the most recent commit for a different implementation of feedback for the user. Upon successfully entering the correct old password and successful submission `SUCCESS: Your password has been changed.` is given in a green color. The incorrect submission of an old password will give `"ERROR: Incorrect password provided. Your password was not changed."` in a red color. this is displayed "Password" title in the profile form.

**Review by nickwxo — APPROVED** [review]

**Comment by nickwxo** [comment]
I just tested this and it seems to be working very well so I've approved this PR. Just made the recommendation to @thinkking to use Bootstrap Alerts (just to be consistent with what we've done elsewhere in the application) but I wouldn't let that prevent merging this into develop.

**Comment by leechristophermurray** [comment]
@nick22891 I will push an update with Bootstrap Alerts soon.

UPDATE: @nick22891 bootstrap alerts are now being used.

**Comment by nickwxo** [comment]
@thinkking I edited the HTML and the CSS classes slightly (to make it look more like the other bootstrap alerts in the application).

**Pull request merged**
